/**
 * Assemble the deployable site — the only build step in this project.
 *
 * docs/ARCHITECTURE.md §1 chose native ES modules with no bundler, and named
 * the conditions to revisit: "if the app grows past ~40 modules … or the
 * @import chain in styles/main.css becomes a visible load delay". Both are now
 * true (47 modules, a 17-deep serial @import chain), and the same paragraph
 * says what to do about it: "add a concatenation step at *deploy* time — not a
 * build step in development."
 *
 * That distinction is the whole design of this file. It runs against a
 * throwaway output directory and never touches `src/`, so development stays
 * `python -m http.server`, the .husky checks keep running on real modules, and
 * anything else that consumes the source tree keeps working unchanged.
 *
 * It also owns the file copying that used to live in the workflow's shell, so
 * that "what ships" has ONE definition — the workflow and tests/bundle.mjs both
 * call this rather than each describing the deploy in their own words.
 *
 * Usage:  node tools/build.mjs [outdir]        default _site
 */

import { build } from "esbuild";
import {
  readFileSync, writeFileSync, mkdirSync, readdirSync,
  statSync, copyFileSync, cpSync, rmSync, existsSync,
} from "node:fs";
import { join, dirname, resolve, relative } from "node:path";
import { gzipSync } from "node:zlib";

const ROOT = resolve(dirname(new URL(import.meta.url).pathname.replace(/^\/([A-Z]:)/, "$1")), "..");
const OUT = resolve(ROOT, process.argv[2] || "_site");

/**
 * Ceiling for the app's EAGER JavaScript, gzipped — what a first-time visitor
 * downloads before the app can start.
 *
 * A budget rather than a report, because "small payload" with no number in the
 * build decays quietly: every addition is individually reasonable and the total
 * is nobody's job. Measured at ~35 KB when this landed; the headroom is for
 * ordinary growth, not for a new dependency.
 */
const EAGER_JS_BUDGET = 45 * 1024;

const rel = f => relative(OUT, f).replace(/\\/g, "/");
const gz = buf => gzipSync(buf, { level: 9 }).length;

rmSync(OUT, { recursive: true, force: true });
mkdirSync(OUT, { recursive: true });

/* ------------------------------------------------------------- copy ----- */

for (const f of [
  "index.html", "app.html", "manifest.webmanifest", "sw.js",
  "robots.txt", "sitemap.xml", "README.md",
  // Read at runtime by src/ui/whatsNew.js, and CHANGELOG.md is what its "full
  // history" link points at. Both are generated by tools/changelog.mjs at
  // release time and committed, so there is nothing to build — only to copy.
  "changelog.json", "CHANGELOG.md",
]) {
  if (existsSync(join(ROOT, f))) copyFileSync(join(ROOT, f), join(OUT, f));
}

// social/ holds the Open Graph card. It lives outside icons/ on purpose:
// icons/ is the PWA icon set and every file in it is precached by the service
// worker, and a share card that only crawlers ever fetch has no business in a
// user's offline cache.
for (const d of ["icons", "docs", "social"]) {
  if (existsSync(join(ROOT, d))) cpSync(join(ROOT, d), join(OUT, d), { recursive: true });
}

// Content sections — help/ and blog/. Each is a directory holding an
// index.html, and the copy takes the articles nested inside it too, so a new
// page needs no change here at all. Found by scanning rather than named one by
// one because a forgotten per-page edit fails silently as a 404 rather than as
// a broken build.
const SKIP = new Set(["node_modules", ".git", ".github", ".husky", ".shots",
                      "src", "icons", "docs", "social", "backend", "tests",
                      "tools", relative(ROOT, OUT)]);
for (const d of readdirSync(ROOT)) {
  if (SKIP.has(d) || !statSync(join(ROOT, d)).isDirectory()) continue;
  if (!existsSync(join(ROOT, d, "index.html"))) continue;
  cpSync(join(ROOT, d), join(OUT, d), { recursive: true });
  console.log("  content page: " + d + "/");
}

// Pages runs Jekyll by default, which ignores files starting with _.
writeFileSync(join(OUT, ".nojekyll"), "");

/* ------------------------------------------------------------ bundle ---- */

const common = {
  bundle: true,
  format: "esm",
  minify: true,
  // Shipped on purpose. They cost a visitor nothing — browsers fetch them only
  // when devtools is open — and they are the deliberate opposite of obfuscating
  // an end-to-end-encrypted app whose entire trust model is that you can read
  // it and check that it does what it claims.
  sourcemap: true,
  // splitting is NOT optional here. Without it esbuild INLINES dynamic imports,
  // which would silently undo every lazy load in the codebase: the globe
  // (landing.js) and files/registry.js + files/transfer.js (main.js). Bundling
  // would then make the payload worse while appearing to have worked.
  splitting: true,
  logLevel: "error",
};

await build({ ...common, entryPoints: [join(ROOT, "src/main.js")], outdir: join(OUT, "src") });
await build({
  ...common,
  // Every module an HTML page names in a <script src> has to be an entry point.
  // The deploy ships bundles, not the source tree, so a module that is only
  // reachable from markup — never imported by another module — is invisible to
  // the bundler and simply will not exist in _site. It 404s on the one page
  // that needs it and nowhere else.
  entryPoints: ["redirect", "landing", "faq", "download"].map(n => join(ROOT, `src/landing/${n}.js`)),
  outdir: join(OUT, "src/landing"),
});

for (const p of ["src/styles/main.css", "src/landing/landing.css"]) {
  await build({
    entryPoints: [join(ROOT, p)],
    outfile: join(OUT, p),
    bundle: true,
    minify: true,
    logLevel: "error",
  });
}

/**
 * The stylesheets that are NOT bundled, because the panel that needs them
 * fetches them on first open — a QR modal's CSS has no business in the critical
 * path of an app most people never open it in.
 *
 * Derived from the `styleHref("…")` calls themselves rather than listed here. A
 * hand-written list is one forgotten line away from a panel rendering unstyled
 * in production and nowhere else, which is not a failure anyone catches quickly.
 */
const lazyCss = new Set();
for (const f of walk(join(ROOT, "src"))) {
  if (!f.endsWith(".js")) continue;
  for (const m of readFileSync(f, "utf8").matchAll(/styleHref\("([^"]+)"\)/g)) lazyCss.add(m[1]);
}
mkdirSync(join(OUT, "src/styles"), { recursive: true });
for (const name of lazyCss) {
  copyFileSync(join(ROOT, "src/styles", name), join(OUT, "src/styles", name));
}

/* --------------------------------------------------- service worker ----- */

/**
 * Stamp VERSION, and rewrite SHELL to what this build actually produced.
 *
 * VERSION: a changed sw.js is what tells the browser an update exists at all,
 * and bumping it by hand is a step someone eventually forgets — which pins
 * every returning user to a stale shell. Stamped from the TAG, so the string a
 * user's cache is keyed on is the same one the app shows in "What's new".
 *
 * SHELL: sw.js ships a hand-maintained list of SOURCE paths, which is right for
 * development — the same worker precaches the unbundled tree there — and wrong
 * for the deploy, where those files no longer exist. `cache.addAll()` rejects
 * as a unit, so one stale entry kills the install and offline support stops
 * working with no visible symptom. Generated for the same reason VERSION is.
 */
const stamp = process.env.GITHUB_REF_TYPE === "tag"
  ? process.env.GITHUB_REF_NAME
  : (process.env.GITHUB_SHA?.slice(0, 12) || "dev");

const shell = [
  "./", "./index.html", "./app.html", "./manifest.webmanifest",
  "./changelog.json", "./CHANGELOG.md",
  ...walk(join(OUT, "src")).filter(f => /\.(js|css)$/.test(f)).map(f => "./" + rel(f)).sort(),
  ...walk(join(OUT, "icons")).map(f => "./" + rel(f)).sort(),
];

const swPath = join(OUT, "sw.js");
let sw = readFileSync(swPath, "utf8");

const withShell = sw.replace(/const SHELL = \[[\s\S]*?\n\];/,
  "const SHELL = [\n" + shell.map(p => `  "${p}",`).join("\n") + "\n];");
if (withShell === sw) die("could not rewrite SHELL in sw.js — the declaration format changed");

const withVersion = withShell.replace(/^const VERSION = ".*";/m, `const VERSION = "${stamp}";`);
if (withVersion === withShell) die("could not stamp VERSION in sw.js — the declaration format changed");

writeFileSync(swPath, withVersion);

/* ------------------------------------------------------------ report ---- */

/**
 * The eager set is main.js plus the chunks it imports STATICALLY. Chunks
 * reachable only through a dynamic import are the lazy ones and are
 * deliberately not counted — counting them would report exactly the payload the
 * split exists to avoid.
 */
const mainJs = readFileSync(join(OUT, "src/main.js"));
const eager = [mainJs, ...[...mainJs.toString().matchAll(/from\s*"\.\/([\w.-]+\.js)"/g)]
  .map(m => readFileSync(join(OUT, "src", m[1])))];
const eagerBytes = gz(Buffer.concat(eager));

console.log("\nBuild\n");
console.log(`  service worker  VERSION = ${stamp}`);
console.log(`  app JS, eager   ${(eagerBytes / 1024).toFixed(1)} KB gzip   (${eager.length} files)`);
console.log(`  app CSS         ${(gz(readFileSync(join(OUT, "src/styles/main.css"))) / 1024).toFixed(1)} KB gzip   (1 file, was a 17-deep @import chain)`);
console.log(`  shell entries   ${shell.length}`);
console.log(`  files to publish ${walk(OUT).length}`);

if (eagerBytes > EAGER_JS_BUDGET) {
  die(`eager JS is ${(eagerBytes / 1024).toFixed(1)} KB gzip, over the `
    + `${(EAGER_JS_BUDGET / 1024).toFixed(0)} KB budget in tools/build.mjs`);
}
console.log(`\n  within budget (${(EAGER_JS_BUDGET / 1024).toFixed(0)} KB)\n`);

function walk(dir, out = []) {
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) walk(full, out);
    else out.push(full);
  }
  return out;
}

function die(msg) {
  console.error(`\n::error::${msg}`);
  process.exit(1);
}
